travel = ['Japan','Tokyo','Kyoto','Marutai','Hokkaido']
print(travel)
print(sorted(travel))
print(travel)
print(sorted(travel,reverse = True))
print(travel)
travel.reverse()
print(travel)
travel.reverse()
print(travel)
travel.sort()
print(travel)
